### PR TITLE
Stability and error handling improvements

### PR DESCRIPTION
**Pull request by roland-vachter**
Try fallback API for local IP detection. If IP detection fails, throw a clear error. Always fallback if klap protocol fails.

### CODE REVIEW

**Comment by roland-vachter** [comment]
Can anyone please have a look at this? Thanks

**Comment by dickydoouk** [comment]
Thanks for your contribution. Looks okay to me. The resolveMacToIp function is only as good as the ARP table it relies on. I believe the find-local-devices module pings all hosts on the subnet to rebuild ARP table, so can often succeed after a retry.

**Comment by roland-vachter** [comment]
Thanks for merging it! Well, I saw that it usually failed on the first call of the function, then it succeeded, but not necessarily on the second attempt, that's why I made a loop to try several times to obtain it. Will you also publish it on npm?

**Comment by roland-vachter** [comment]
@dickydoouk could you please publish a new version to npm?

**Comment by dickydoouk** [comment]
That should be published now as part of v2.0.7 https://www.npmjs.com/package/tp-link-tapo-connect

**Pull request merged**
